### ISSUE TITLE
No colors in iTerm2

### ISSUE THREAD

**Issue by kristofferek** [ericwenn/chalmersfood#1]
<img width="285" alt="skarmavbild 2017-11-17 kl 10 23 54" src="https://user-images.githubusercontent.com/14162376/32939948-75879e9c-cb81-11e7-824f-dcc6efc01ba9.png">

no colors no fun. fix pls

**Comment by ericwenn** [comment]
Fixed in https://github.com/ericwenn/chalmersfood/commit/8ceade9201b557940eaf60b80c776f23ff5d92a1
